version: '3'

volumes:
  cache:
    driver: local

services:
  app:
    build:
      context: .
    container_name: JRProject
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/world
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
    ports:
      - '8080:8080'
  db:
    image: mysql
    container_name: mysqlContainer
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DB=world
  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass bGFic2ZpdWFnaWxydWdiYWlmZGI=
    volumes:
      - cache:/data
